# Generated by Django 5.2.8 on 2025-11-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_id_muestra', models.CharField(max_length=50, unique=True)),
                ('raza', models.CharField(max_length=100)),
                ('RP', models.CharField(blank=True, max_length=50, null=True)),
                ('BU', models.CharField(blank=True, max_length=50, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1)),
                ('imagen_muestra', models.ImageField(blank=True, null=True, upload_to='muestras/')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudAnalisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_solicitante', models.CharField(max_length=100)),
                ('email_solicitante', models.EmailField(max_length=254)),
                ('tipo_solicitud', models.CharField(choices=[('padre', 'Verificación con padre'), ('padre_madre', 'Verificación con padre y madre'), ('buscar_padre', 'Búsqueda de padre'), ('buscar_madre', 'Búsqueda de madre')], max_length=20)),
                ('tipo_muestra', models.CharField(choices=[('sangre', 'Sangre'), ('pelo', 'Pelo'), ('saliva', 'Saliva'), ('hisopado', 'Hisopado'), ('otro', 'Otro')], max_length=20)),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('datos_adicionales', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
